name = "atorvo"
main = "worker.js"
compatibility_date = "2024-10-01"

kv_namespaces = [
  { binding = "KV", id = "ac197a3f5a6d4f82b5586970f780beeb" }
]

[assets]
binding = "ASSETS"
directory = "./"


[build]
command = "npm test"

[observability.logs]
enabled = true
