name = "atorvo"
main = "worker.js"
compatibility_date = "2024-10-01"

[[kv_namespaces]]
binding = "KV"
id = "kv"
preview_id = "kv"

[assets]
binding = "ASSETS"
directory = "./"


[build]
command = "npm test"

[observability.logs]
enabled = true
